In [1]:
import pandas as pd

In [8]:
# DATA COLLECTION PHASE

dataset=pd.read_csv("Salary_Data.csv")

# pd=class

# read csv=function

# pd.read_csv refers - The function read_csv is called from the class pd.

# The dataset file is passed within the bracket with double quotes("Salary_Data.csv")

In [9]:
dataset

# To view datas or content in the dataset file, or can display using print statement.

# displays all the column and rows as input and output.

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [10]:
#INPUT SPLIT

independent=dataset[["YearsExperience"]]

# Assigning independent variable, also it is input.
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [11]:
# OUTPUT SPLIT

dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [12]:
# TRAINING AND TEST SET SPLIT UP

from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test= train_test_split(independent,dependent,test_size=0.30,random_state=0)

# sklearn is a library function.
# sklearn supports Machine Learning.
# it is importing only train and test function from the folder modelselection under sklearn.
# Only required functions are called rather all functions like pandas, therfore memory consuption will be less.

# X_train=training set input
# X_test =test set input
# y_train= training set output
# y_test = test set output

In [13]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [14]:
weight=regressor.coef_
weight

array([[9360.26128619]])